project:
  type: website

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/boi-doingthings
      - icon: twitter
        href: https://twitter.com/boi_doingthings
format:
  html:
    theme: darkly
    css: styles.css



